services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    shm_size: 512mb
    env_file:
      - .env
    volumes:
      - ./services/db/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"